doctrine_mongodb:
  auto_generate_proxy_classes: false
  auto_generate_hydrator_classes: false
  connections:
    default:
      server: '%env(resolve:MONGODB_URL)%'
      options: {}
  default_database: '%env(resolve:MONGODB_DB)%'
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          dir: '%kernel.project_dir%/src/Document'
          prefix: 'App\Document'
          is_bundle: false
