framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    trusted_proxies: ~
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']

    # Sécuriser la connexion avec HSTS (Strict Transport Security)
    # Ajout de headers de sécurité dans la configuration du framework
    # je n'ajoute pas directement `http` ici, mais il faut gérer les headers via un listener
    
    
    # Configuration des sessions
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

# Configuration spécifique pour l'environnement de test
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
