#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: ../src/Controller/
    type: attribute
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
